FROM ros:galactic

# COPY requirements.txt ./

RUN apt-get update && apt-get install python3-pip -y
# RUN pip install --no-cache-dir -r requirements.txt

# RUN mkdir /benchmarks

# COPY . .

# CMD ["python3", "./requests_client.py"]
