version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
  client:
    build: ./client
    network_mode: host
    depends_on:
      - server
    volumes:
      - "./client/benchmarks/:/benchmarks"

